# Generated by Django 5.2 on 2025-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_advance_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
