# Generated by Django 5.2 on 2025-04-11 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_is_advance_refunded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='loans_payme_due_dat_2c16be_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='loans_payme_status_94aae6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
