# Generated by Django 5.2 on 2025-04-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='application_date',
        ),
    ]
