# Generated by Django 5.2 on 2025-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_remove_loan_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom interest rate per lakh (leave blank for standard rate)', max_digits=5, null=True),
        ),
    ]
